export const styles = {
  container: {
    padding: '32px',
    maxWidth: '1100px',
    margin: '40px auto',
    background: '#fff',
    borderRadius: '18px',
    boxShadow: '0 4px 24px rgba(60,72,88,0.10)',
    fontFamily: 'Inter, Arial, sans-serif',
  },
  title: {
    marginBottom: '28px',
    color: '#1a2233',
    fontSize: '2rem',
    fontWeight: 700,
    letterSpacing: '0.5px',
    textAlign: 'center',
  },
  table: {
    width: '100%',
    borderCollapse: 'separate',
    borderSpacing: 0,
    background: '#f9fafb',
    borderRadius: '12px',
    overflow: 'hidden',
    boxShadow: '0 1px 4px rgba(60,72,88,0.06)',
  },
  tableHeader: {
    background: 'linear-gradient(90deg, #e3e9f7 0%, #f5f7fa 100%)',
  },
  tableHeaderCell: {
    padding: '16px 18px',
    color: '#1a2233',
    fontWeight: 600,
    fontSize: '1.05rem',
    borderBottom: '2px solid #e3e9f7',
    textAlign: 'left',
  },
  tableRow: (index) => ({
    background: index % 2 === 0 ? '#fff' : '#f4f6fb',
    transition: 'all 0.2s ease',
    cursor: 'pointer',
    ':hover': {
      background: '#d1e7ff',
      borderLeft: '4px solid #4a90e2',
      transform: 'translateX(2px)',
      boxShadow: '0 2px 8px rgba(74, 144, 226, 0.15)',
    },
  }),
  tableCell: {
    padding: '14px 18px',
    color: '#2d3e50',
    fontSize: '1rem',
    borderBottom: '1px solid #e3e9f7',
  },
  emptyState: {
    padding: '32px',
    textAlign: 'center',
    color: '#8a94a6',
    background: '#f4f6fb',
    borderRadius: '10px',
    fontSize: '1.1rem',
    marginTop: '18px',
  },
  loading: {
    textAlign: 'center',
    color: '#4a90e2',
    fontSize: '1.2rem',
    padding: '32px',
  },
  error: {
    textAlign: 'center',
    color: '#e24a4a',
    fontWeight: 600,
    fontSize: '1.2rem',
    padding: '32px',
    background: '#fff0f0',
    borderRadius: '10px',
    marginTop: '18px',
  },
  backButton: {
    background: '#f4f6fb',
    border: '1px solid #e3e9f7',
    padding: '10px 15px',
    borderRadius: '8px',
    color: '#2d3e50',
    cursor: 'pointer',
    fontWeight: 600,
    marginBottom: '20px',
    transition: 'background 0.2s',
    ':hover': {
      background: '#e9f0fb',
    },
  },
  downloadButton: {
    background: '#4a90e2',
    border: 'none',
    padding: '10px 15px',
    borderRadius: '8px',
    color: '#fff',
    cursor: 'pointer',
    fontWeight: 600,
    transition: 'background 0.2s',
    ':hover': {
      background: '#357abd',
    },
  },
  buttonContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '20px',
  },
  detailContainer: {
    padding: '20px',
    background: '#f9fafb',
    borderRadius: '12px',
  },
  detailItem: {
    padding: '10px 0',
    borderBottom: '1px solid #e3e9f7',
    ':last-child': {
      borderBottom: 'none',
    },
    color: '#2d3e50',
    fontSize: '1rem',
  },
}; 